### ISSUE TITLE
The behavior of running the application without arguments is not described in the documentation

### ISSUE THREAD

**Issue by silvuss** [caderek/gramma#2]
After running the application without arguments, there appeared a blank line. The application seemed to not do anything. After pressing ENTER again, there appeared the following string in a new line:
```
No mistakes found!
```
After that, there appeared the command prompt, which may mean that the application terminates (I cannot be sure).

This behavior is not described in the documentation, and  – for me – seems to be counterintuitive.

### Actual behavior

The documentation has no description about what happening and/or what is going to happen when run in the console without arguments.

### Expected behavior

The documentation contains the following information described:
- is it expected that the application be run without arguments;
- what shall happen when running it without arguments.

**Comment by caderek** [comment]
Thanks, it is rather standard behavior - it works like `cat` and other *nix commands - it waits for input stream and then does its thing. But I should definitely clarify that.

**Comment by caderek** [comment]
@silvuss Let me know if this clarifies the docs: https://github.com/caderek/gramma/pull/3/commits/aba95ab987d0262c01f4ee95a7ae3e1b120272f8

**Comment by caderek** [comment]
Ok, closing - will reopen if needed.

**Comment by silvuss** [comment]
@caderek Thanks, this seems to me to be enough for this issue. :)
