### ISSUE TITLE
PORT support on `gramma server start`

### ISSUE THREAD

**Issue by azu** [caderek/gramma#29]
**Is your feature request related to a problem? Please describe.**

Currently, port number is hardcoded `8081`.

https://github.com/caderek/gramma/blob/3023e3ae7db87c9acd3989762669d229894cae83/src/server/startServer.js#L35-L37

**Describe the solution you'd like**
I want to use another port number like following.

```
gramma server start --port 12345
```

**Describe alternatives you've considered**

```
PORT=12345 gramma server start
```

**Additional context**

📝 Current `gramma server start` does not show the port number of languagetools server.
if the port number is conflicted, the user can not know the local server url.

```
$ gramma server start
Starting local API server...
Waiting for local API server...
Waiting for local API server...
API server started! PID: 55069
```

**Comment by azu** [comment]
Fmm, `8081` is popular port.
Often  port is conflicted and use another port like `8082`.

I want to use gramma in my computer. 
It means that I need to write the port into config or source code.

```js
const gramma = require("gramma")

gramma
  .check("Some text to check.", {
    api_url: "http://localhost:13451/v2/check" // if the port is random, it is hard to use
  })
  .then(console.log)
```

It requres that always use specific unused port like 13451 in my global.

For example, I've created [textlint-rule/textlint-rule-gramma](https://github.com/textlint-rule/textlint-rule-gramma).
This tool have used gramma.  If the user want to use local gramma, how to set the `api_url`?
`"api_url": "http://localhost:8081/v2/check"` will be broken if `8081` is used by another program.

Of course, I can stop the another program that use 8081.
However, `--port`  is common feature in server program.
Actually, LanguageTool server support it.

**Comment by caderek** [comment]
Ok, it's a valid concern - I will merge the PR, but have to tweak it a bit before I update npm package and binaries.

**Comment by caderek** [comment]
New version is available!

**Comment by azu** [comment]
Thanks!
