### ISSUE TITLE
The website https://caderek.github.io/gramma/ is not mentioned neither in the README nor in the project

### ISSUE THREAD

**Issue by silvuss** [caderek/gramma#4]
This project has a separate official website: https://caderek.github.io/gramma/. But, I did not find it in the README or anywhere else in the project here (on GitHub). If I am right, then a user that encounters this project here probably has no chance to find its website.

### Actual behavior

The website https://caderek.github.io/gramma/ is not mentioned in the README or anywhere else in this project on GitHub.

### Expected behavior

The website https://caderek.github.io/gramma/ is mentioned in the README and/or in the field "Website" on the tab "Code" (next to the project title).

**Comment by caderek** [comment]
Added to the project, can't add to README because I use autogenerated page based on README itself (i would be weird if the website would link to itself). Thanks!

**Comment by silvuss** [comment]
@caderek OK, I understand.
