### ISSUE TITLE
There are links for getting specific versions of the application in the section "Installation" of the README

### ISSUE THREAD

**Issue by silvuss** [caderek/gramma#7]
In the section "Installation", there are put links for getting specific versions of the application. In general, this is not a bug; but these links are already outdated, and I am worrying that they will remain so. If they will, this may be confusing for the reader, and shall be considered a bug.

### Actual behavior

The section "Instalation" of the README contains links for getting specific versions of the application.

### Expected behavior

The section "Instalation" of the README does not contain links for getting specific versions of the application. Instead, there may be put information about getting new versions of the application from the page with releases.

**Comment by caderek** [comment]
Well, I knew that I will forget about that;) You are right, better to link to release page - less error-prone

**Comment by caderek** [comment]
Ok, I added correct links to the README. After some thoughts, I think that is a better approach (easier for user) - I will figure out some automatic system to not make that mistake again. Thanks for the quick reaction!

**Comment by silvuss** [comment]
Thanks. Well, I forgot that packages available through the npm website has a place for the description there.

So, should I understand that for every new version, you will maintain both the links in the npm's README and the links in the GitHub's README?
