### ISSUE TITLE
Pressing the ESCAPE key in the "check mode" causes the application to terminate with an exception

### ISSUE THREAD

**Issue by silvuss** [caderek/gramma#9]
### Steps to reproduce

1. Run the application with the following command:

    ```
    gramma check "."
    ```

2. Press the ESCAPE key.

### Actual behavior

The application terminates, and the output contains a stack trace, starting with the following:
```
(node:12393) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
...
```

### Expected behavior

I do not know whether all the described behavior or only part of it is a bug. The README does not contain information about possible behavior of any key. Possibilities of expected behavior are:
- If all of the behavior is a bug – the ESCAPE key should not cause the application to terminate – then the expected behavior is both not to terminate, and to print some appropriate message (e.g. `This key is not handled`) or to print nothing at all.
- If only part of the behavior is a bug – the ESCAPE key should terminate the application, but there should be no stack trace printed – then the expected behavior is just to print some appropriate message (e.g. `This key is not handled`) or to print nothing at all.

### Notes

As I have observed, this behavior happen not only using `gramma check`, but I have not checked all the possible cases, so I leave for the author finding the scope of this behavior.

---

**UPDATE:** This problem happens also with the combination CTRL+D. But, since I cannot currently make the application work, I cannot confirm whether the stack trace is the same. I will try that later.

**Comment by caderek** [comment]
Fixed all cases of errors on abort with version 1.0.0
